# Generated by Django 2.2.10 on 2020-02-27 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200227_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 17, 3, 23, 159681), verbose_name='创建时间'),
        ),
    ]
